<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fbs</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>Flatbuffers</string>
	<key>patterns</key>
	<array>
    <dict>
      <key>match</key>
      <string>\b(table)\b([a-zA-Z_][a-zA-Z0-9_]*))</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.table.fbs</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.fbs</string>
        </dict>
      </dict>
    </dict>
		<dict>
			<key>match</key>
			<string>\b(namespace|root_type|rpc_service|file_extension|file_identifier|enum|table)\b</string>
			<key>name</key>
			<string>keyword.other.fbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:(\[)?(bool|u?byte|u?short|u?int(8|16|32|64)|u?long|float(32|64)?|double|string)(\])?</string>
			<key>name</key>
			<string>storage.type.builtin.fbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:(\[)?([a-zA-Z_][a-zA-Z0-9_]*)(\])?</string>
			<key>name</key>
			<string>storage.type.custom.fbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.fbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-?[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.fbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-?[0-9]+.[0-9]+((e|E)(+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.float.fbs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.fbs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.fbs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.fbs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fbs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.fbs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.fbs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.fbs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{)(\})</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fbs</string>
	<key>uuid</key>
	<string>DF45B3F4-A2D8-4E27-935E-683E40BAC22A</string>
</dict>
</plist>
